tasks:
  - name: Gitpod installer
    before: TASKS="browser+snowsql"; eval "$(curl -s https://gitpod.5ha.re/before?tasks=$TASKS)"
    init: eval "$(curl -s https://gitpod.5ha.re/init?tasks=$TASKS)"
    command: eval "$(curl -s https://gitpod.5ha.re/command?tasks=$TASKS)"
  - command: |
      source .gitpod/setup_environment.sh
      .gitpod/setup_snowsql.py
  - init: |
      python -m venv .venv
      source .venv/bin/activate
      pip install --upgrade pip
      pip install -r requirements.txt
    command: |
      exit
image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - ms-python.python
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: false
    addComment: false
    addBadge: false
