tasks:
  - init: |
      workdir="$(pwd)"
      tmpdir="$(mktemp -d)"
      polydir=/workspace/polynote
    command: |
      exit
image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - ms-python.python
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: false
    addComment: false
    addBadge: false
