tasks:
  - init: |
      workdir="$(pwd)"
      tmpdir="$(mktemp -d)"
      # Create venv; cannot use --upgrade-deps with current version of Python
      python -m venv .venv
      source .venv/bin/activate
      pip install --upgrade pip
      pip install -r requirements.txt
      rm -r $tmpdir
    command: |
      exit
image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - ms-python.python
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: false
    addComment: false
    addBadge: false
